'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CreateBatch
    
    '''<summary>
    '''ddlBProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBProduct As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DisplayProductionOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DisplayProductionOrders As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblProductionOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductionOrders As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''grdvProductionOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdvProductionOrders As Global.System.Web.UI.WebControls.GridView
End Class
