'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DisplayBatchBundles
    
    '''<summary>
    '''displaybatchprodn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents displaybatchprodn As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblgrdbatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblgrdbatch As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''grdvbatchprodn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdvbatchprodn As Global.System.Web.UI.WebControls.GridView
End Class
