'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CMTDataCapture
    
    '''<summary>
    '''lblBundleNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBundleNo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtorderNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtorderNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBatchNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBatchNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtProdcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProdcode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtProdDescr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProdDescr As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblj2c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblj2c As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtJtoCut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJtoCut As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblajc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblajc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtAJCutD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAJCutD As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSize As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtYarnColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYarnColour As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCSIM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCSIM As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblOperation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOperation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblerrajce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblerrajce As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblajce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblajce As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtactualJcut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtactualJcut As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnCaptureBundle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCaptureBundle As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblerrJDmsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblerrJDmsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RBLJD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBLJD As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''lblerrJrsyadj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblerrJrsyadj As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblJrsyadj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJrsyadj As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReason As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblerrother control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblerrother As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblother control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblother As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtotherR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtotherR As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnjrsyadj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnjrsyadj As Global.System.Web.UI.WebControls.LinkButton
End Class
