'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CMTJob
    
    '''<summary>
    '''btncutting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btncutting As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnattachVN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnattachVN As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnSideseam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSideseam As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnPressing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPressing As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnDispatchs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDispatchs As Global.System.Web.UI.WebControls.LinkButton
End Class
