'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CMTOverveiw
    
    '''<summary>
    '''ddlCMTStaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCMTStaff As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LblJDisc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblJDisc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''displayCMTbatches control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents displayCMTbatches As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblgrdbatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblgrdbatch As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''grdvCMTbatches control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdvCMTbatches As Global.System.Web.UI.WebControls.GridView
End Class
