'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ApproveJrsyDiff
    
    '''<summary>
    '''ReasonDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReasonDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lblBatch4Inv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBatch4Inv As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblerrJDiff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblerrJDiff As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DisplaygrdvJDiff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DisplaygrdvJDiff As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''grdvJDiff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdvJDiff As Global.System.Web.UI.WebControls.GridView
End Class
