'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CreateInvoice
    
    '''<summary>
    '''ddlBatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBatch As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblBatch4Inv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBatch4Inv As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblerrBatch4Inv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblerrBatch4Inv As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DisplaygrdvBatch4Inv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DisplaygrdvBatch4Inv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''grdvBatch4Inv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdvBatch4Inv As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''txtjerseycost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtjerseycost As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btncreateINV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btncreateINV As Global.System.Web.UI.WebControls.LinkButton
End Class
