'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Recieve_yarn
    
    '''<summary>
    '''ddlSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSupplier As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtYtype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYtype As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTtweight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTtweight As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTtcartons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTtcartons As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtkgprice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtkgprice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtYdyelot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYdyelot As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlYcolour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlYcolour As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''sqlYcolour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlYcolour As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''txtYweight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYweight As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtYcartons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYcartons As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtYCweight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYCweight As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtYCcartons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYCcartons As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnCapture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCapture As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''displayInvoiceDyelots control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents displayInvoiceDyelots As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblMyTickets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMyTickets As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''grdvInvoiceDyelots control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdvInvoiceDyelots As Global.System.Web.UI.WebControls.GridView
End Class
