'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CheckDataCapture
    
    '''<summary>
    '''lblBundleNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBundleNo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtorderNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtorderNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBatchNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBatchNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtProdcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProdcode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtProdDescr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProdDescr As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPToMake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPToMake As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPMade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPMade As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSize As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtComponent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComponent As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtQPpanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQPpanel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKwidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKwidth As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtkLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtkLength As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtYarnColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYarnColour As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblerrother control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblerrother As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblerrchecker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblerrchecker As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlChecker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlChecker As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblerrfault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblerrfault As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlFault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFault As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtFHoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFHoles As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFNeedleStripe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFNeedleStripe As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFWidth As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFLength As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFDropStitch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFDropStitch As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFYarn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFYarn As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFPressoff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFPressoff As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFQty As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFaultCollars control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFaultCollars As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFOthers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFOthers As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblerrBweight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblerrBweight As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtBundleWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBundleWeight As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBundleWasteWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBundleWasteWeight As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBundleFaultWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBundleFaultWeight As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnCaptureBundle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCaptureBundle As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBack As Global.System.Web.UI.WebControls.LinkButton
End Class
